export const EVENT_LABELS = {
  nav: "Навигация",
  backHome: "Басты бетке",
  eventDetails: "Шара мәліметтері",
  date: "Күні",
  time: "Уақыты",
  venue: "Орын",
  dressCode: "Киім үлгісі",
  buildRoute: "Маршрут құру",
  countdownTitle: "Шараға дейін",
  countdownAria: "Шараға дейінгі уақыт",
  countdownDays: "күн",
  countdownHours: "сағат",
  countdownMinutes: "минут",
  countdownSeconds: "секунд",
  rsvpTitle: "Қатысуды растау",
  footerLove: "Сүйіспеншілікпен",
  musicOn: "Музыканы қосу",
  musicOff: "Музыканы өшіру",
} as const

export const RSVP_LABELS = {
  name: "Аты-жөніңіз",
  namePlaceholder: "Аты-жөні",
  attending: "Қатыса аласыз ба?",
  yes: "Келемін",
  no: "Кела алмаймын",
  guests: "Қонақтар саны",
  wish: "Жастарға тілек",
  wishOptional: "(міндетті емес)",
  wishPlaceholder: "Жылы сөздеріңіз...",
  submit: "Жіберу",
  submitting: "Жіберілуде...",
  thanks: "Рахмет!",
  successYes: "Жауабыңыз қабылданды. Бұл күнді бізбен бірге өткізетіндігіңізге қуаныштымыз!",
  successNo: "Жауабыңыз қабылданды. Сізді сағынып қалады, жылы сөздеріңізге рахмет!",
  errorSubmit: "Жіберу сәтсіз аяқталды",
} as const
